apiVersion: v1
kind: ServiceAccount
metadata:
  name: aspnetapp-sa
  namespace: dotnet-demo
  labels:
    app: aspnetapp
# Opt out of automounting the SA token into every pod.
# We'll mount it explicitly only where needed.
automountServiceAccountToken: false
